User.destroy_all
Game.destroy_all

jack = User.create username: "Jack", password_string: "admin", hint: "because you're the boss around here"
reed = User.create username: "Reed", password_string: "admin", hint: "because you're the boss around here"
jon = User.create username: "Jon", password_string: "doomslayer", hint: "something about a dog"
kyle = User.create username: "Kyle", password_string: "password", hint: "not a very good password"

# BlackJack Seeds
Game.create user_id: jack.id, game_type: "BlackJack", result: "win"
Game.create user_id: jack.id, game_type: "BlackJack", result: "win"
Game.create user_id: reed.id, game_type: "BlackJack", result: "win"
Game.create user_id: reed.id, game_type: "BlackJack", result: "win"
Game.create user_id: reed.id, game_type: "BlackJack", result: "win"
Game.create user_id: kyle.id, game_type: "BlackJack", result: "win"
Game.create user_id: kyle.id, game_type: "BlackJack", result: "win"
Game.create user_id: kyle.id, game_type: "BlackJack", result: "win"
Game.create user_id: jon.id, game_type: "BlackJack", result: "win"
Game.create user_id: jon.id, game_type: "BlackJack", result: "win"
Game.create user_id: reed.id, game_type: "BlackJack", result: "win"
Game.create user_id: reed.id, game_type: "BlackJack", result: "win"
Game.create user_id: jon.id, game_type: "BlackJack", result: "loss"
Game.create user_id: kyle.id, game_type: "BlackJack", result: "win"
Game.create user_id: jon.id, game_type: "BlackJack", result: "loss"
Game.create user_id: kyle.id, game_type: "BlackJack", result: "win"
Game.create user_id: jon.id, game_type: "BlackJack", result: "win"
Game.create user_id: jack.id, game_type: "BlackJack", result: "loss"
Game.create user_id: kyle.id, game_type: "BlackJack", result: "loss"
Game.create user_id: jon.id, game_type: "BlackJack", result: "loss"
Game.create user_id: kyle.id, game_type: "BlackJack", result: "win"
Game.create user_id: jon.id, game_type: "BlackJack", result: "loss"
Game.create user_id: kyle.id, game_type: "BlackJack", result: "loss"
Game.create user_id: jon.id, game_type: "BlackJack", result: "loss"
Game.create user_id: jon.id, game_type: "BlackJack", result: "loss"
Game.create user_id: jack.id, game_type: "BlackJack", result: "win"
Game.create user_id: reed.id, game_type: "BlackJack", result: "win"
Game.create user_id: jack.id, game_type: "BlackJack", result: "loss"

# War Seeds
Game.create user_id: jack.id, game_type: "War", result: "win"
Game.create user_id: jack.id, game_type: "War", result: "win"
Game.create user_id: jack.id, game_type: "War", result: "win"
Game.create user_id: reed.id, game_type: "War", result: "win"
Game.create user_id: reed.id, game_type: "War", result: "win"
Game.create user_id: kyle.id, game_type: "War", result: "win"
Game.create user_id: kyle.id, game_type: "War", result: "win"
Game.create user_id: jon.id, game_type: "War", result: "win"
Game.create user_id: jon.id, game_type: "War", result: "win"
Game.create user_id: jon.id, game_type: "War", result: "win"
Game.create user_id: reed.id, game_type: "War", result: "win"
Game.create user_id: reed.id, game_type: "War", result: "win"
Game.create user_id: kyle.id, game_type: "War", result: "loss"
Game.create user_id: kyle.id, game_type: "War", result: "win"
Game.create user_id: jon.id, game_type: "War", result: "loss"
Game.create user_id: jon.id, game_type: "War", result: "win"
Game.create user_id: jon.id, game_type: "War", result: "win"
Game.create user_id: reed.id, game_type: "War", result: "loss"
Game.create user_id: reed.id, game_type: "War", result: "loss"
Game.create user_id: kyle.id, game_type: "War", result: "loss"
Game.create user_id: kyle.id, game_type: "War", result: "win"
Game.create user_id: jon.id, game_type: "War", result: "loss"
Game.create user_id: jon.id, game_type: "War", result: "loss"
Game.create user_id: jon.id, game_type: "War", result: "loss"
Game.create user_id: jack.id, game_type: "War", result: "loss"
Game.create user_id: jack.id, game_type: "War", result: "win"
Game.create user_id: jack.id, game_type: "War", result: "win"
Game.create user_id: jack.id, game_type: "War", result: "loss"